### PR TITLE
adding support for multiple row delimiters

### PR DESCRIPTION
**Pull request by vamzz1**
Issue: https://github.com/wdavidw/node-csv/issues/216

### CODE REVIEW

**Comment by wdavidw** [comment]
Thanks for the pull request, before I could accept, please takes those notes into consideration
- dont modify existing tests when that's possible, only add new tests (at least when that make sense)
- be backward compatible, meaning if rowDelemiters is a string, convert it to an array (just after line 76)

**Comment by vamzz1** [comment]
Pushed the changes suggested.

**Comment by vamzz1** [comment]
Pushed the suggested changes.

**Comment by wdavidw** [comment]
One more request (I realise that I'm getting extremely picky). Could you merge those [3 commits into one](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/)

**Comment by vamzz1** [comment]
Done.

**Comment by vamzz1** [comment]
Made the changes you suggested.

**Comment by wdavidw** [comment]
thanks for your hard work

**Pull request merged**
