### PR TITLE
Add promise wrapper

### PR DESCRIPTION
**Pull request by ufo22940268**
Add a promise wrapper to parse csv file.

### CODE REVIEW

**Comment by wdavidw** [comment]
Thank you for your contribution. I'll do it differently:
- do not read from a file but accept a buffer or a string
- rely on './lib/sync.js'
- no fixture in tests, data are inlined with the tests
- source will be named './src/promise.coffee.md'
- no yarn file
If you feel like updating this pr, then please go ahead, otherwise I'll do it myself in the next few days.

**Comment by ufo22940268** [comment]
[this](https://github.com/wdavidw/node-csv-parse/blob/master/samples/callback.js) demo already provide api to parse from string. All we need to do is `promisify` this function.

**Comment by alechirsch** [comment]
@wdavidw Is this going anywhere? Would be nice for this package to support promises, async/await

**Comment by wdavidw** [comment]
Promise is useless for this library but I might take the time to do it one day. I've done some tests a few months ago, my conclusion is that `async/await` is nativelly working since we are implementing the Node.js stream API, just not documented. You can view it [here](https://github.com/adaltas/node-csv-parse/blob/master/bench/async.iterator.js#L24-L33).

**Comment by wdavidw** [comment]
I am still to find a real usage of promise with this library. There is one that I can think of but none came with it. However, I might add promise in the future if I find the time for it but coming with a legitimate example will boost my motivation. More like please add promise because it is new and cool. What would be interesting is to work with iterators.

**Comment by wdavidw** [comment]
You can take a look at the [async iterator sample](https://github.com/adaltas/node-csv-parse/blob/master/samples/async.iterator.js)

**Comment by joewagner** [comment]
@wdavidw The most compelling reason to add the Promise rapper is to enable use with async/await.  Here is an example:

```
(async function () {
    const parse = require('../lib')
    const assert = require('assert')

    const input = '#Welcome\n"1","2","3","4"\n"a","b","c","d"'
    const ouput = await parse(input, {
        comment: '#'
    });

    assert.deepEqual(
        output,
        [ [ '1', '2', '3', '4' ], [ 'a', 'b', 'c', 'd' ] ]
    )
});
```

Thanks, Hope this helps

**Comment by wdavidw** [comment]
And here is how to achieve the same goal, with the same performance and with less code:

```js
const parse = require('../lib/sync')
const assert = require('assert')

const input = '#Welcome\n"1","2","3","4"\n"a","b","c","d"'
const ouput = parse(input, {
    comment: '#'
});

assert.deepEqual(
    output,
    [ [ '1', '2', '3', '4' ], [ 'a', 'b', 'c', 'd' ] ]
)
```

**Comment by joewagner** [comment]
@wdavidw I didn't realize you could do it this!  Thank you

**Comment by alechirsch** [comment]
@wdavidw @joewagner That code is synchronous (I/O blocking). If you have a server that takes in csv files, the server will be unresponsive until the parsing is complete. I do not tihnk moving to synchronous code is the solution to this.

**Comment by joewagner** [comment]
@alechirsch My current use case calls `parse` in a job runner process which works fine with blocking code, but I agree it would be convenient to be able to use `await`

**Comment by wdavidw** [comment]
@alechirsch there is no IO in the parser, there is absolutely nothing blocking in the parser, whichever the module you choose. If you need something scalable, use the stream api. If you don't, go for the sync API, it will behave just the same as streaming with a promise, saturating the memory if the dataset is too large and having to wait for the parsing of the all dataset before working with it.

**Pull request closed without merging**
