### PR TITLE
Adding feature to avoid unwanted parsing when there is wrong delimiter or row delimiter provided in the options

### PR DESCRIPTION
**Pull request by ajitkaller**
Hi David,

We use node-csv-parse module in our project to parse the csv file data that helps to get each line passed back on the basis of row delimiter and the delimiters (',' or can be overridden by passing in the options). But while using the module we came across a scenario where if the options is passed with the rowDelimiter and the columnDelimiter but that does not match the csv data that is parsed from the file. If the file is too big, we just wait for readStream and at csv-parse end you just keep on buffering the data into fields/line. So we thought we can avoid this by limiting the parsing. I have set the max data that can be read as 250K and if we do not encounter any delimier/rowDelimiter throwing back the error. 

I hope I have explained to my best. Please do consider my request and let me know if you have any suggestion or query.

Thanks,
Ajit

### CODE REVIEW

**Comment by wdavidw** [comment]
This is great, thanks. Could you just convert the sample into a testcase?

**Comment by ajitkaller** [comment]
Hi David,

I have added a new option max_limit_on_data_read that can be passed in the options. In case the value is not set, default value set is 250K data. I have added the testcase to test this enhancement in the code added. Having this option property that can be set to limit the parsing of data helped to have a small file in the samples to have this functionality tested.

Thanks,
Ajit

**Comment by wdavidw** [comment]
could you explain me why do you say "250K data" while the value is "128000". The comments say "bt default maxLimitOnDataRead is set to 128000 considering max data read can be 250K", could you clarify, i dont get it?
Also, i have remove the sample and simplify a bit the testcase (without external dependencies).
Finaly, on the website, the options description is:
*   `max_limit_on_data_read` (int)   
    Maximum numer of characters to be contained in the field and line buffers
    before an exception is raised, used to guard against a wrong delimiter or
    rowDelimiter, default to 128000 characters.   
Feel free to suggest sth else.

**Comment by ajitkaller** [comment]
Thanks David for considering my idea. Coming to the value 128000, actually according to ECMA-262 3rd Edition Specification, each character represents a single 16-bit unit of UTF-16 text. Considering this, 
250K of data = 256000 Bytes and 
having said each character takes 2 Bytes of data, I have hardcoded it to 128000.

Thanks for the minor changes to the PR, that makes more sense.

**Comment by wdavidw** [comment]
I was sure javascript was utf8. Let's just speak about bytes then and not characteres in the doc, thanks

**Pull request merged**
