### PR TITLE
Issue #73 Throw an error when a column is missing

### PR DESCRIPTION
**Pull request by geniass**
Issue #73 Error when number of columns is inconsistent

### CODE REVIEW

**Comment by wdavidw** [comment]
seems reasonnable, please prepare a test reproducing your enhancement and I will merge your contribution

**Comment by geniass** [comment]
I just realised that my changes cause some of the quotes tests to fail since they are using data with an inconsistent number of lines. Should I change those tests as well?

**Comment by AGhost-7** [comment]
I think this should be optional instead as its breaking existing tests. Like a "strict" parser mode or something.

**Comment by tejasmanohar** [comment]
Agree w/ @AGhost-7

**Comment by wdavidw** [comment]
By definition, the parser expect a valid CSV so I agree that modifying the wrong test to pass is the way to go.

**Comment by wdavidw** [comment]
We could implement support for incohérent line number in relax mode.

**Comment by ovidiubute** [comment]
Hey guys, I just noticed this change during my build. This has the potential to break a lot of parsing of, let's say, inconsistent CSV data originating from, for example, a public dataset. Some lines can have empty values in the columns, while the next lines don't have the values for those columns at all. Until today this was fine, but now the parser will throw an error on the first shorter line. While I totally agree ignoring variable column number during parsing may be dangerous, some data is simply inconsistent  and it's an unreasonable effort to fix it for the purpose of parsing.

I would make this a 'strict' mode parsing and offer a more forgiving option (like it was done pre-merge) as the default.

**Comment by AGhost-7** [comment]
@wdavidw A csv is still valid if there are inconsistent columns. For what its worth, in terms of specifications for the CSV format (you can google for the RFC), there is no mention of columns requiring to be of the same length for each row.

**Comment by tejasmanohar** [comment]
I think this should've only be shipped once it has a toggle / flag in front of it.

**Comment by geniass** [comment]
@AGhost-7 Are you referring to RFC4180? It says "Each line should contain the same number of fields throughout the file".

However if this is breaking existing software, then I agree, there probably should be a toggle and/or a warning in the readme.

**Comment by wdavidw** [comment]
So what about introducing a new option like "relax_column_count" (suggestions welcome) while still maintaining by default the behavior introduced in this commit?

**Comment by wdavidw** [comment]
Please have a look at [commit 84ea8fdaff1c88e58970f4bcef92c429b2cf220f](https://github.com/wdavidw/node-csv-parse/commit/84ea8fdaff1c88e58970f4bcef92c429b2cf220f), does publishing it as version 1.0.6 is a suitable solution to everyone ?

**Comment by tejasmanohar** [comment]
+1

**Comment by tejasmanohar** [comment]
I think this option should be made off by default in the patch commit (1.0.6) and if you'd like, on by default in a major version like 1.1.0. Just to avoid people's builds failing with semver ranges in package.json.

**Comment by wdavidw** [comment]
@tejasmanohar, just to confrm i understood you, option "relax_column_count" is "false" by default in HEAD. what you're suggesting is setting it to "true" which behave like version 1.0.4 and setting it to "false" for version 1.1.0?

**Comment by tejasmanohar** [comment]
@wdavidw exactly

**Comment by wdavidw** [comment]
done

**Comment by tejasmanohar** [comment]
awesome!! 🎉

**Comment by Koslun** [comment]
Bit late to the party but isn't it rather best practise rather to follow the npm guidelines listed at [npm](https://docs.npmjs.com/getting-started/semantic-versioning) and later directly linked to [semver homepage](http://semver.org/). Meaning: 

Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.

In this case thus meaning 1.1.0 for the version that adds the functionality but defaults to not using it because it's a breaking change. And 2.0.0 for when the default instead is the new stricter way. Figure a deprecation message too for the 1.1.0 version in this case.

Recognize that many libraries instead blur the line on this rather than adhere to semver, but am I maybe missing something in this case? Is the change maybe just too small? Or do we make the slight exception because the new error is the intended behavior and this is rather just fixing an unintentional bug that unfortunately breaks some people's tests?

**Comment by wdavidw** [comment]
While increasing to a minor version, I didnt consider this as a breaking change, just enforcing CSV validation. I understand this is arguable.

**Comment by chrisfosterelli** [comment]
Changing behaviour from "works with this particular CSV" to "throws an error with this particular CSV" is definitely a breaking change. Just found out our script has been crashing half way through for the last month due to this :(

**Pull request merged**
