### PR TITLE
Implement `raw` option

### PR DESCRIPTION
**Pull request by AGhost-7**
This adds a `raw` option which will make each csv row parsed into an object containing two properties:
- `raw`: a string which is the original data that was parsed.
- `row`: an array _or_ object (depending on other options used) which is the parsed row.

Fixes issue #85

### CODE REVIEW

**Comment by tejasmanohar** [comment]
I'd prefer `parsed` to `row`, but +1 for this PR. Super useful for debugging. // cc @wdavidw

**Comment by wdavidw** [comment]
Thanks, why is rowBuf in line 163 and 167 and not just after line [160](https://github.com/wdavidw/node-csv-parse/pull/88/files#diff-f35c5932bb4da98c9da8192a6851d827R160) ?

**Comment by CExJBoudreau** [comment]
@wdavidw For rawBuf I only clear it if I'm done with it. For line 163 and 167 it exits early so I clear it there, otherwise it gets cleared at line 183.

**Comment by AGhost-7** [comment]
@wdavidw For rawBuf I only clear it if I'm done with it. For line 163 and 167 it exits early so I clear it there, otherwise it gets cleared at line 183.

**Comment by AGhost-7** [comment]
@wdavidw Is there something wrong with the PR? At work this would be really useful for debugging data imports.

**Comment by wdavidw** [comment]
One thing, line 234, there is a reference to `@raw` which i dont see anywhere else.

**Pull request merged**
