### PR TITLE
Added skipped line count

### PR DESCRIPTION
**Pull request by behcet-li**

### CODE REVIEW

**Comment by wdavidw** [comment]
Could you explain me the case behind this?

**Comment by behcet-li** [comment]
I have to deal with documents which contain a lot of malformed lines. This will provide basic information about how many lines were skipped due to errors vs how many were actually processed.

**Comment by wdavidw** [comment]
Thanks, I now undestand the motivation. I do have a few questions:
1. Could you confirm that you are not altering any current behavior, just adding a counter? Also, I'll rather rename it to a more specific name like "skipped_column_count".
2. We need a test illustrating the usage of "skipped_column_count".
3. You are adding a new test but it doesnt seem directly related. I'm not against adding more test to the suite but that shall be presented inside a separate issue.
4. Dont modifiy an existing test, write a new one

**Comment by behcet-li** [comment]
1. Besides tests I can not further proof that existing behavior has changed. This fork seems to work fine on my end as well.

2, 3, 4. Created a new test suite, added couple tests. Let me know if it needs further testing

**Comment by wdavidw** [comment]
By "could you confirm that you are not altering any current behavior", I didn't meant to justify yourself. It was a real question.

**Comment by wdavidw** [comment]
Could you revert your changes in "test/write.coffee". Why did you made this change? If pertinent, you can add a new one.

**Comment by behcet-li** [comment]
I changed _test/write.coffee_ because it was failing on 0.10.x.

**Comment by wdavidw** [comment]
ok, we can keep it then. before i merge, could you rebase your change an latest head. the file changes include my previous commit which doesnt seem right (unless i'm mistaken on how github handle this)

**Comment by behcet-li** [comment]
Yeah it looks suspicious to me also. It started happening after I rebased from upstream but it should be the same after the merge.

**Comment by wdavidw** [comment]
didn't work well, i got double commit, strange behavior

**Comment by behcet-li** [comment]
```git log --left-right --graph --cherry-pick --oneline master...HEAD~8```

I'm not entirely sure but looks like we're seeing double commits because they come from a fork, although I rebased them back in from master in the first place. Weird but overall code looks as expected.

**Pull request merged**
